### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by LoonyMender** [MichaPipo/Generative_Gif_Engine#4]
Is there any way to remove the transparency feature when converting the spritesheet to a gif. I've played around with it so much but it's really messing everything up. I've attached the spritesheet, any help would be really appreciated!

![1](https://user-images.githubusercontent.com/34894732/148684024-8b02bdf3-641c-4400-ad5a-fda1bbd1a96a.png)

**Comment by JAYxTHExAK** [comment]
We’re you able to figure this out? I am having the same issues.
